BlogFall/Areas/Admin/Controllers/CategoriesController.cs
using BlogFall.Attributes;
using BlogFall.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BlogFall.Areas.Admin.Controllers
{
    [BreadCrumb("Kategoriler")]
    public class CategoriesController : AdminBaseController
    {
        // GET: Admin/Categories
        [BreadCrumb("İndeks")]
        public ActionResult Index()
        {
            return View(db.Categories.OrderByDescending(x => x.CategoryName).ToList());
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var category = db.Categories.Find(id);

            if (category == null)
            {
                return HttpNotFound();
            }

            if (category.Posts.Count > 0)
            {
                return Json(new { success = false, error = "Silmek istediğiniz kategoride yazılar bulunduğundan silinememektedir." });
            }
            db.Categories.Remove(category);
            db.SaveChanges();

            return Json(new { success = true });


        }
        [BreadCrumb("Yeni")]
        public ActionResult New()
        {
            return View("Edit", new Category());
        }

        [HttpPost, ValidateAntiForgeryToken]
        [BreadCrumb("Yeni")]
        public ActionResult New(Category model)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(model);
                db.SaveChanges();
                TempData["successMessage"] = "Yeni kategori başarıyla oluşturuldu";
                return RedirectToAction("Index");
            }

            return View("Edit", model);
        }

        [BreadCrumb("Düzenle")]
        public ActionResult Edit(int id)
        {
            return View("Edit",db.Categories.Find(id));
        }

        [HttpPost, ValidateAntiForgeryToken]
        [BreadCrumb("Düzenle")]
        public ActionResult Edit(Category model)
        {
            if (ModelState.IsValid)
            {
                db.Entry(model).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TempData["successMessage"] = "Kategori adı başarıyla değiştirildi.";

                return RedirectToAction("Index");
            }
            return View("Edit", model);
        }
    }
}

BlogFall/Areas/Admin/Controllers/CommentsController.cs
using BlogFall.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogFall.Areas.Admin.Controllers
{
    [BreadCrumb("Yorumlar")]
    public class CommentsController : AdminBaseController
    {
        // GET: Admin/Comments
        [BreadCrumb("İndeks")]
        public ActionResult Index()
        {
            return View(db.Comments.ToList());
        }
    }
}

BlogFall/Areas/Admin/Controllers/DashboardController.cs
using BlogFall.Areas.Admin.ViewModels;
using BlogFall.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogFall.Areas.Admin.Controllers
{
    [BreadCrumb("Ana Sayfa")]
    public class DashboardController : AdminBaseController
    {
        // GET: Admin/Dashboard
        [BreadCrumb("İndeks")]
        public ActionResult Index()
        {
            var model = new DashboardIndexViewModel
            {
                CategoryCount = db.Categories.Count(),
                PostCount = db.Posts.Count(),
                UserCount = db.Users.Count(),
                CommentCount = db.Comments.Count(),
            };
            return View(model);
        }
    }
}

BlogFall/Areas/Admin/Controllers/PostsController.cs
using BlogFall.Areas.Admin.ViewModels;
using BlogFall.Attributes;
using BlogFall.Models;
using BlogFall.Utility;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace BlogFall.Areas.Admin.Controllers
{
    public class PostsController : AdminBaseController
    {
        // GET: Admin/Posts
        [BreadCrumb("Yazılar")]
        public ActionResult Index()
        {
            // todo: datatable orderby string int datetime
            return View(db.Posts.OrderByDescending(x => x.CreationTime).ToList());
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var post = db.Posts.Find(id);

            if(post == null)
            {
                return HttpNotFound();
            }

            db.Posts.Remove(post);    
            db.SaveChanges();

            return Json(new { success = true });
          
        }

        [BreadCrumb("Düzenle")]
        public ActionResult Edit(int id)
        {
            ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "CategoryName");

            PostEditViewModel vm = db.Posts.Select(x => new PostEditViewModel
            {
                Id = x.Id,
                CategoryId = x.CategoryId,
                Content = x.Content,
                Title = x.Title,
                Slug = x.Slug
            }).FirstOrDefault(x => x.Id == id);

            return View(vm);
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        [BreadCrumb("Düzenle")]
        public ActionResult Edit(PostEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Post post = db.Posts.Find(model.Id);

                post.Content = model.Content;
                post.CategoryId = model.CategoryId;
                post.Title = model.Title;
                post.Slug = model.Slug;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "CategoryName");
            return View();
        }

        [BreadCrumb("Yeni")]
        public ActionResult New()
        {
            ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "CategoryName");
            return View("Edit", new PostEditViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [BreadCrumb("İndeks")]
        public ActionResult New( PostEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Post post = new Post
                {
                    Title = model.Title,
                    Content = model.Content,
                    CategoryId = model.CategoryId,
                    AuthorId = User.Identity.GetUserId(),
                    CreationTime = DateTime.Now,
                    Slug = model.Slug
                };

                db.Posts.Add(post);
                db.SaveChanges();

                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "CategoryName");
            return View("Edit", new PostEditViewModel());
        }
        
        [HttpPost]
        public ActionResult AjaxImageUpload(HttpPostedFileBase file)
        {
            if (file == null || file.ContentLength == 0 || !file.ContentType.StartsWith("image/"))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var saveFolderPath = Server.MapPath("~/Upload/Posts");
            var ext = Path.GetExtension(file.FileName);
            var saveFileName = Guid.NewGuid() + ext;
            var saveFilePath = Path.Combine(saveFolderPath, saveFileName);
            file.SaveAs(saveFilePath);

            return Json(new { url = Url.Content("~/Upload/Posts/" + saveFileName) });

        }

        [HttpPost]
        public ActionResult GenerateSlug(string title)
        {
            return Json(UrlService.URLFriendly(title));
        }
    }
}

BlogFall/Areas/Admin/Controllers/UsersController.cs
using BlogFall.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BlogFall.Areas.Admin.Controllers
{
    [BreadCrumb("Kullanıclar")]
    public class UsersController : AdminBaseController
    {
        [BreadCrumb("İndeks")]
        public ActionResult Index()
        {
            return View(db.Users.ToList());
        }

        public ActionResult ChangeStatus(string userId, bool isEnabled)
        {
            var user = db.Users.Find(userId);
            user.IsEnabled = isEnabled;
            db.SaveChanges();
            return Json(new { success = true });
        }
    }
}

BlogFall/Areas/Admin/Views/Dashboard/Index.cshtml
@model DashboardIndexViewModel
@{
    ViewBag.Title = "Anasayfa";
    ViewBag.HeaderTitle = "Yönetim Paneli";
}

<!-- Small boxes (Stat box) -->
<div class="row">
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
            <div class="inner">
                <h3>@Model.CategoryCount</h3>

                <p>Kategori</p>
            </div>
            <div class="icon">
                <i class="fas fa-folder"></i>
            </div>
            <a href="@Url.Action("Index","Categories")" class="small-box-footer">Detaylı bilgi <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h3>@Model.PostCount<sup style="font-size: 20px"></sup></h3>

                <p>Yazı</p>
            </div>
            <div class="icon">
                <i class="fas fa-file-alt"></i>
            </div>
            <a href="@Url.Action("Index","Posts")" class="small-box-footer">Detaylı bilgi <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-warning">
            <div class="inner">
                <h3>@Model.UserCount</h3>

                <p>Kullanıcı</p>
            </div>
            <div class="icon">
                <i class="fas fa-user-alt"></i>
            </div>
            <a href=""@Url.Action("Index","Users")" class="small-box-footer">Detaylı bilgi <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-danger">
            <div class="inner">
                <h3>@Model.CommentCount</h3>

                <p>Yorum</p>
            </div>
            <div class="icon">
                <i class="fas fa-comments"></i>
            </div>
            <a href="@Url.Action("Index","Comments")" class="small-box-footer">Detaylı bilgi <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<!-- /.row -->